const PORTFOLIO = {
  current: 127400,
  goal: 1000000,
  ytdReturn: 27.4,
  monthsLeft: 9.5,
  requiredMonthly: 18.2,
  cash: 14,
  winRate: 74,
  totalSignals: 156
};

const STOCKS = [
  {
    ticker: "NVDA",
    name: "NVIDIA Corp",
    signal: "BUY",
    conf: 94,
    entry: 142.50,
    target: 178.00,
    stop: 128.00,
    tf: "SHORT",
    price: 143.82,
    change: +3.21,
    risk: "LOW",
    sector: "Tech",
    pos: 8.5,
    reason: "AI catalyst plus momentum breakout above 200MA. Institutional volume surge confirms accumulation. Strong setup with asymmetric risk/reward."
  },
  {
    ticker: "PLTR",
    name: "Palantir Technologies",
    signal: "BUY",
    conf: 89,
    entry: 118.00,
    target: 155.00,
    stop: 105.00,
    tf: "SHORT",
    price: 121.40,
    change: +4.18,
    risk: "MED",
    sector: "Tech",
    pos: 5.0,
    reason: "Government AI contracts expanding aggressively. AIP platform gaining enterprise traction. Enter on any pullback to $118–$120."
  },
  {
    ticker: "MSFT",
    name: "Microsoft Corp",
    signal: "BUY",
    conf: 82,
    entry: 415.00,
    target: 490.00,
    stop: 390.00,
    tf: "LONG",
    price: 421.30,
    change: +0.94,
    risk: "LOW",
    sector: "Tech",
    pos: 6.0,
    reason: "Azure growth reaccelerating. Copilot monetization just beginning. Blue chip with strong momentum and defensive characteristics."
  },
  {
    ticker: "META",
    name: "Meta Platforms",
    signal: "BUY",
    conf: 87,
    entry: 592.00,
    target: 680.00,
    stop: 558.00,
    tf: "SHORT",
    price: 598.45,
    change: +1.87,
    risk: "LOW",
    sector: "Tech",
    pos: 7.0,
    reason: "Revenue acceleration driven by AI-powered ad targeting. Margin expansion narrative intact. Strong breakout from recent consolidation."
  },
  {
    ticker: "CRWD",
    name: "CrowdStrike Holdings",
    signal: "BUY",
    conf: 85,
    entry: 395.00,
    target: 465.00,
    stop: 372.00,
    tf: "SHORT",
    price: 401.20,
    change: +2.14,
    risk: "MED",
    sector: "Security",
    pos: 5.0,
    reason: "Cybersecurity spend accelerating. Recovery complete post-incident. Strong ARR growth and platform consolidation play."
  },
  {
    ticker: "TSLA",
    name: "Tesla Inc",
    signal: "SELL",
    conf: 81,
    entry: 390.00,
    target: 290.00,
    stop: 415.00,
    tf: "SHORT",
    price: 388.20,
    change: -2.44,
    risk: "HIGH",
    sector: "Auto",
    pos: 0,
    reason: "Delivery misses plus margin compression worsening. Technical breakdown below key $395 support. Exit immediately. Do not average down."
  },
  {
    ticker: "AAPL",
    name: "Apple Inc",
    signal: "HOLD",
    conf: 63,
    entry: 185.00,
    target: 215.00,
    stop: 172.00,
    tf: "LONG",
    price: 212.80,
    change: -0.32,
    risk: "MED",
    sector: "Tech",
    pos: 5.0,
    reason: "Consolidating near highs. AI features not moving the needle yet. China uncertainty remains. Maintain existing position, no new entries."
  },
  {
    ticker: "AMZN",
    name: "Amazon.com",
    signal: "HOLD",
    conf: 70,
    entry: 195.00,
    target: 240.00,
    stop: 182.00,
    tf: "LONG",
    price: 201.50,
    change: +0.61,
    risk: "MED",
    sector: "Tech",
    pos: 4.5,
    reason: "AWS growth solid but ad segment uncertain. Wait for Q2 earnings catalyst before adding exposure."
  }
];